const userActionType = {
    LOGIN_REQUEST: 'USER_LOGIN_REQUEST',
    LOGIN_SUCCESS: 'USER_LOGIN_SUCCESS',
    LOGIN_FAILURE: 'USER_LOGIN_FAILURE',

    LOGOUT: 'USERS_LOGOUT',

    GET_ALL_REQUEST: 'USER_GET_ALL_REQUEST',
    GET_ALL_SUCCESS: 'USER_GET_ALL_SUCCESS',
    GET_ALL_FAILURE: 'USER_GET_ALL_FAILURE'
}

export default userActionType;